name: Wholesome Messages

on:

  schedule:

    - cron: "0 9 * * *"

jobs:

  generate_message:

    runs-on: ubuntu-latest

    steps:

    - name: Checkout repository

      uses: actions/checkout@v2

    - name: Set up Python

      uses: actions/setup-python@v2

      with:

        python-version: 3.x

    - name: Install dependencies

      run: pip install -r requirements.txt  # Update with your specific requirements file, if any

    - name: Run Wholesome Messages script

      run: |

        python wholesome_messages.py > message.txt

        cat message.txt

