name: Discord User Info

on:

  push:

    branches:

      - main

jobs:

  generate_info:

    runs-on: ubuntu-latest

    steps:

    - name: Checkout repository

      uses: actions/checkout@v2

    - name: Set up Python

      uses: actions/setup-python@v2

      with:

        python-version: 3.x

    - name: Install dependencies

      run: pip install -r requirements.txt

    - name: Run Discord User Info Finder script

      run: python discord_user_info.py

      env:

        DISCORD_BOT_TOKEN: ${{ secrets.DISCORD_BOT_TOKEN }}
